### ISSUE TITLE
Only be able to have one tooltip open at the time

### ISSUE THREAD

**Issue by Martin36** [Martin36/StoryLines#62]
When the user clicks on the "v" symbol of the cards the dropdown appears. If this is done for multiple cards it will show multiple dropdowns at the same time. This should not happen. So when the user selects another card to show the dropdown the previously opened dropdown should be hidden. 

I am currently working on new dropdowns for the page.

**Comment by karishma-jain** [comment]
Can you plz explain a bit in detail?
