### ISSUE TITLE
Error when trying to add the same label to a card that it already has

### ISSUE THREAD

**Issue by Martin36** [Martin36/StoryLines#70]
POST https://api.trello.com/1/cards/58f684ea2ae50607d7ac0bdd/labels?color=green&name=low%20priority 400 ()

**Comment by Sandsten** [comment]
Also "TypeError: Cannot read property 'toLowerCase' of undefined" when trying to add the same label without changing it first.

**Comment by Sandsten** [comment]
Each card has two variables, label and labels. Can we update the variable label in the API? I guess labels are the available ones for that card and label is the assigned one, or can you have multiple assigned ones? Labels should only be updated once I guess, with all available ones.
